version: "3.9"
services:
  swagger-ui-watcher:
    build: ./
    image: swagger-ui-watcher
    container_name: nestjs_output_with_openapi_ui_watcher
    ports:
      - 8000:8000
    volumes:
      - ../api-server/openapi:/openapi
    command: /openapi/openapi-spec.yaml

  swagger-api:
    image: stoplight/prism:3
    container_name: "nestjs_output_with_openapi_api"
    ports:
      - 4010:4010
    command: mock -h 0.0.0.0 /openapi-spec.yaml
    volumes:
      - ../api-server/openapi/openapi-spec.yaml:/openapi-spec.yaml
